package com.Horted.app.Domain;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;

@Entity
public class Plants {

	/**
	 * The field 'Id' is the primary key for Plants
	 * it is automatically generated by 'GeneratedValue'
	 */
	@Id
	@GeneratedValue
	int Id;

	private String apiId;
	
	private String imageURL;
	
	private String name;
	
	private String Border;
	
	private String wateringFrequency;
	
	private LocalDate wateringTime;
	
	private int daysToNextWater;
	
	private boolean happinessToday = false;
	
	@OneToMany(cascade=CascadeType.ALL)
	@JoinColumn
	private List<PlantLog> logs = new ArrayList<>(); //OneToMany relationship - One plant can have many logs
	
	@OneToMany(cascade=CascadeType.ALL)
	@JoinColumn
	private List<PlantHappiness> happy = new ArrayList<>(); //OneToMany relationship - One plant can have many logs
		
	public List<PlantHappiness> getHappy() {
		return happy;
	}
	public void setHappy(List<PlantHappiness> happy) {
		this.happy = happy;
	}
	public int getId() {
		return Id;
		
	}
	public String getApiId() {
		return apiId;
	}

	public void setApiId(String apiId) {
		this.apiId = apiId;
	}

	public String getImageURL() {
		return imageURL;
	}

	public void setImageURL(String imageURL) {
		this.imageURL = imageURL;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getBorder() {
		return Border;
	}

	public void setBorder(String border) {
		Border = border;
	}

	public LocalDate getWateringTime() {
		return wateringTime;
	}

	public void setWateringTime(LocalDate wateringTime) {
		this.wateringTime = wateringTime;
	}

	public String getWateringFrequency() {
		return wateringFrequency;
	}

	public void setWateringFrequency(String wateringFrequency) {
		this.wateringFrequency = wateringFrequency;
	}

	public int getDaysToNextWater() {
		return daysToNextWater;
	}

	public void setDaysToNextWater(int daysToNextWater) {
		this.daysToNextWater = daysToNextWater;
	}
	public boolean isHappinessToday() {
		return happinessToday;
	}
	public void setHappinessToday(boolean happinessToday) {
		this.happinessToday = happinessToday;
	}
	
	public List<PlantLog> getLogs() {
		return logs;
	}
	public void setLogs(List<PlantLog> logs) {
		this.logs = logs;
	}
	
	
}
